<a href="https://colab.research.google.com/github/empLittlewhite/as-a-beginner/blob/main/%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

In [64]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [65]:
x[3]

tensor(3)

In [66]:
len(x)

4

In [67]:
x.shape

torch.Size([4])

In [68]:
A = torch.arange(20).reshape(5,4)
A


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [69]:
#转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [70]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [71]:
B == B.T


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [72]:
x = torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [73]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()#分配新内存，将A的副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [74]:
a = 2
x = torch.arange(24).reshape(2,3,4)
a+x,(a*x).shape


(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [75]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [76]:
#按照某一个轴进行计算
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [77]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [78]:
A = torch.arange(20).reshape(5,4)
sum_A = A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])

In [79]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [80]:
#  点积  dot-product
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [81]:
torch.sum(x * y)

tensor(6.)

In [82]:
# matrix vector
# A.shape,x.shape,torch.mv(A,x)

In [84]:
# 矩阵乘法
B = torch.ones(4,3)
# torch.mm(A,B)

In [86]:
# 范数 矩阵的长度
u = torch.tensor([3.0,-4.0])
torch.norm(u)

# L1范数，元素绝对值之和
torch.abs(u).sum()

tensor(7.)

In [87]:
# F范数 所有元素平方求和再根号
torch.norm(torch.ones((4,9)))

tensor(6.)

In [88]:
a = torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [90]:
# axis=1 就是去除第二列元素
a.sum(axis=0).shape

torch.Size([5, 4])

In [93]:
# keepdims=True，中间的元素变成了1
a.sum(axis=[0,2],keepdims=True).shape

torch.Size([1, 5, 1])