<a href="https://colab.research.google.com/github/empLittlewhite/as-a-beginner/blob/main/%E7%9F%A9%E9%98%B5%E8%AE%A1%E7%AE%97%E3%80%81%E6%B1%82%E5%AF%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
# 保存梯度,并访问梯度
# 等价于 x = torch.arange(4.0,requires_grad=True)
x.requires_grad_(True)
x.grad

In [3]:
y = 2 * torch.dot(x,x)#求内积 y=2x^2
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
# 调用反向传播函数自动计算y关于x每一个分量的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4*x

tensor([True, True, True, True])

In [6]:
# 重写内容_,将x的梯度清零
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [7]:
# 大部分只是对标量求导，不会对矩阵进行求导，这里只是范例
# 计算的基本是loss，都是标量。
x.grad.zero_()
y = x * x
y.sum().backward()#这里的sum就是标量
x.grad

tensor([0., 2., 4., 6.])

In [10]:
# 将一些计算移动到计算图之外，可以进行参数固定的作用
x.grad.zero_()
y = x * x
# 将y视作一个常数 就是x*x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u #求导的结果就是常数

tensor([True, True, True, True])

In [12]:
# 即使构建函数的计算图需要通过Python控制流，依然可以计算得到变量的梯度
def f(a):
  b = a * 2
  while b.norm() < 1000:
    b = b *2
    if b.sum() > 0:
      c = bi
    else:
      c = 100 * b
    return c
a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()

a.grad == d/a

tensor(True)